routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//////////////////
// ROOT CONTEXT //
//////////////////

Route::group(
    [
        'as'         => 'root.',
        'prefix'     => 'root',
        'namespace'  => 'Root',
        'middleware' => ['role:root'],
    ],
    function () {
        Route::get('dashboard', [
            'as'   => 'dashboard',
            'uses' => 'RootController@getIndex',
        ]);

        Route::get('sudo/{userId}', [
            'as'   => 'sudo',
            'uses' => 'RootController@getSudo',
        ])->where('userId', '\d*');
    }
);

//////////////////
// REGULAR AUTH //
//////////////////

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//////////
// AJAX //
//////////

Route::group(['namespace' => 'API'], function () {

    Route::post('booking', [
        'as'   => 'api.booking.action',
        'uses' => 'BookingController@postAction',
    ]);
});

///////////////////
// GUEST CONTEXT //
///////////////////

Route::group([], function () {

    ///////////////////////////
    // PRIVATE HOME / WIZARD //
    ///////////////////////////

    Route::get('home', ['as' => 'home', 'uses' => 'User\WizardController@getWizard'])->middleware('auth');

    ///////////////////////
    // LANGUAGE SWITCHER //
    ///////////////////////

    Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

    /////////////////
    // SOCIAL AUTH //
    /////////////////

    Route::get('social/login/redirect/{provider}', [
        'as'   => 'social.login',
        'uses' => 'Auth\OAuthController@redirectToProvider',
    ]);

    Route::get('social/login/{provider}', 'Auth\OAuthController@handleProviderCallback');

    /////////////////
    // PUBLIC HOME //
    /////////////////

    Route::get('/', 'WelcomeController@index');

    ///////////////////////////////////////
    // WHOOPS USER FRIENDLY ERROR SCREEN //
    ///////////////////////////////////////

    Route::get('whoops', [
        'as'   => 'whoops',
        'uses' => 'WhoopsController@display',
    ]);
});

//////////////////
// USER CONTEXT //
//////////////////

Route::group(['prefix' => 'user', 'middleware' => ['auth']], function () {

    // USER PREFERENCES
    Route::get('preferences', [
        'as'   => 'user.preferences',
        'uses' => 'User\UserPreferencesController@getPreferences',
        ]);
    Route::post('preferences', [
        'as'   => 'user.preferences',
        'uses' => 'User\UserPreferencesController@postPreferences',
        ]);

    Route::get('agenda', [
        'as'   => 'user.agenda',
        'uses' => 'User\AgendaController@getIndex',
    ]);
    Route::get('businesses/register/{plan?}', [
        'as'   => 'manager.business.register',
        'uses' => 'Manager\BusinessController@create',
    ]);
    Route::post('businesses/register', [
        'as'   => 'manager.business.store',
        'uses' => 'Manager\BusinessController@store',
    ]);
    Route::get('businesses', [
        'as'   => 'manager.business.index',
        'uses' => 'Manager\BusinessController@index',
    ]);
    Route::get('directory', [
        'as'   => 'user.directory.list',
        'uses' => 'User\BusinessController@getList',
    ]);
    Route::get('subscriptions', [
        'as'   => 'user.subscriptions',
        'uses' => 'User\BusinessController@getSubscriptions',
    ]);
    Route::get('dashboard', [
        'as'   => 'user.dashboard',
        'uses' => 'User\WizardController@getDashboard',
    ]);

    ////////////
    // WIZARD //
    ////////////
    Route::group(['as' => 'wizard.'], function () {
        Route::get('terms', [
            'as'   => 'terms',
            'uses' => 'User\WizardController@getTerms',
        ]);
        Route::get('wizard', [
            'as'   => 'welcome',
            'uses' => 'User\WizardController@getWelcome',
        ]);
        Route::get('pricing', [
            'as'   => 'pricing',
            'uses' => 'User\WizardController@getPricing',
        ]);
    });
});

////////////////////////////////////
// SELECTED BUSINESS SLUG CONTEXT //
////////////////////////////////////

Route::group(['prefix' => '{business}'], function ($business) {

    Route::get('ical/{token}', [
        'as'   => 'business.ical.download',
        'uses' => 'User\ICalController@download',
    ]);

    ///////////////////////////
    // BUSINESS USER CONTEXT //
    ///////////////////////////

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {

        // BOOKINGS
        Route::group(['prefix' => 'agenda', 'as' => 'booking.'], function () {
            Route::post('store', [
                'as'   => 'store',
                'uses' => 'AgendaController@postStore',
            ]);
            Route::get('book', [
                'as'   => 'book',
                'uses' => 'AgendaController@getAvailability',
            ]);
            Route::get('validate', [
                'as'   => 'validate',
                'uses' => 'AgendaController@getValidate',
            ]);
        });

        // BUSINESSES
        Route::group(['prefix' => 'businesses', 'as' => 'businesses.'], function () {
            Route::get('home', [
                'as'   => 'home',
                'uses' => 'BusinessController@getHome',
            ]);
        });
    });

    ////////////////////
    // USER RESOURCES //
    ////////////////////

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {

        Route::get('contact', [
            'as'   => 'business.contact.index',
            'uses' => 'ContactController@index',
        ]);
        Route::get('contact/create', [
            'as'   => 'business.contact.create',
            'uses' => 'ContactController@create',
        ]);
        Route::post('contact', [
            'as'   => 'business.contact.store',
            'uses' => 'ContactController@store',
        ]);
        Route::get('contact/{contact}', [
            'as'   => 'business.contact.show',
            'uses' => 'ContactController@show',
        ]);
        Route::get('contact/{contact}/edit', [
            'as'   => 'business.contact.edit',
            'uses' => 'ContactController@edit',
        ]);
        Route::put('contact/{contact}', [
            'as'   => 'business.contact.update',
            'uses' => 'ContactController@update',
        ]);
        Route::delete('contact/{contact}', [
            'as'   => 'business.contact.destroy',
            'uses' => 'ContactController@destroy',
        ]);
    });

    //////////////////////////////
    // BUSINESS MANAGER CONTEXT //
    //////////////////////////////

    Route::group(['prefix' => 'manage', 'namespace' => 'Manager'], function () {

        // BUSINESS PREFERENCES
        Route::get('preferences', [
            'as'   => 'manager.business.preferences',
            'uses' => 'BusinessPreferencesController@getPreferences',
            ]);
        Route::post('preferences', [
            'as'   => 'manager.business.preferences',
            'uses' => 'BusinessPreferencesController@postPreferences',
            ]);

        // AGENDA
        Route::get('agenda', [
            'as'   => 'manager.business.agenda.index',
            'uses' => 'BusinessAgendaController@getIndex',
        ]);
        Route::get('calendar', [
            'as'   => 'manager.business.agenda.calendar',
            'uses' => 'BusinessAgendaController@getCalendar',
        ]);

        // BUSINESS MANAGEMENT
        Route::get('dashboard', [
            'as'   => 'manager.business.show',
            'uses' => 'BusinessController@show',
        ]);
        Route::get('edit', [
            'as'   => 'manager.business.edit',
            'uses' => 'BusinessController@edit',
        ]);
        Route::put('', [
            'as'   => 'manager.business.update',
            'uses' => 'BusinessController@update',
        ]);
        Route::delete('', [
            'as'   => 'manager.business.destroy',
            'uses' => 'BusinessController@destroy',
        ]);

        // BUSINESS NOTIFICATIONS
        Route::get('notifications', [
            'as'   => 'manager.business.notifications.show',
            'uses' => 'BusinessNotificationsController@show',
            ]);

        // SEARCH
        Route::post('search', [
            'as'   => 'manager.search',
            'uses' => 'Search@postSearch',
        ]);

        // ADDRESSBOOK / CONTACT RESOURCE
        Route::group(['prefix' => 'contact'], function () {
            Route::get('', [
                'as'   => 'manager.addressbook.index',
                'uses' => 'AddressbookController@index',
            ]);
            Route::get('create', [
                'as'   => 'manager.addressbook.create',
                'uses' => 'AddressbookController@create',
            ]);
            Route::post('', [
                'as'   => 'manager.addressbook.store',
                'uses' => 'AddressbookController@store',
            ]);
            Route::get('{contact}', [
                'as'   => 'manager.addressbook.show',
                'uses' => 'AddressbookController@show',
            ]);
            Route::get('{contact}/edit', [
                'as'   => 'manager.addressbook.edit',
                'uses' => 'AddressbookController@edit',
            ]);
            Route::put('{contact}', [
                'as'   => 'manager.addressbook.update',
                'uses' => 'AddressbookController@update',
            ]);
            Route::delete('{contact}', [
                'as'   => 'manager.addressbook.destroy',

resources/views/_errors.blade.php
{{-- Validation Error Messages --}}

{{--
    trans('app.msg.invalid_token')
--}}

@if (count($errors) > 0)
<div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
{{-- Validation Error Messages --}}

resources/views/_footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <strong>Desarrollado por <a href="http://artisan.com.ar">Artisan</a></strong>
</footer>

resources/views/_navi18n.blade.php
{{-- Language Switcher Dropdown --}}
<li id="navLang" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        {{ $availableLanguages[$appLocale] }} <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
    @foreach ($availableLanguages as $locale => $language)
        @if ($locale != $appLocale)
        <li>
            {!! link_to_route('lang.switch', $language, $locale) !!}
        </li>
        @endif
    @endforeach
    </ul>
</li>
{{-- Language Switcher Dropdown --}} 

resources/views/_user-account-menu.blade.php
<!-- User Account Menu -->
<li class="dropdown user user-menu">
    <!-- Menu Toggle Button -->
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <!-- The user image in the navbar-->
        <img src="{{ $gravatarURL }}" class="user-image" alt="{{ $user->name }}">
        <!-- hidden-xs hides the username on small devices so only the image appears. -->
        <span class="hidden-xs">{{ $user->name }}</span>
    </a>
    <ul class="dropdown-menu">
        <!-- The user image in the menu -->
        <li class="user-header">
            <img src="{{ $gravatarURL }}" class="img-circle" alt="{{ $user->name }}">

            <p title="{{ $timezone }}">{{ $user->name }}</p>
            <p><small>{{ $user->email }}</small></p>
        </li>
        <!-- Menu Body -->
        <li class="user-body">
            <div class="row">
                <div class="col-xs-4 text-center">
                    <a href="{{ route('manager.business.index') }}">{{ trans('app.nav.manager.business.menu') }}</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#"></a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="{{ docs_url(Session::get('language')) }}" target="_blank">{{ trans('app.nav.manual') }}</a>
                </div>
            </div>
            <!-- /.row -->
        </li>
        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <a href="{{ route('user.preferences') }}" class="btn btn-default btn-flat">{{ trans('app.nav.preferences') }}</a>
            </div>
            <div class="pull-right">
                <a href="{{ url('/logout') }}" class="btn btn-default btn-flat">{{ trans('app.nav.logout') }}</a>
            </div>
        </li>
    </ul>
</li>

resources/views/whoops.blade.php
@extends('layouts.bare')

@section('css')
@parent
<style type="text/css">
.error {
  margin: 0 auto;
  text-align: center;
}

.error-code {
  bottom: 60%;
  color: #2d353c;
  font-size: 96px;
  line-height: 100px;
}

.error-desc {
  font-size: 12px;
  color: #647788;
}

.m-b-10 {
  margin-bottom: 10px!important;
}

.m-b-20 {
  margin-bottom: 20px!important;
}

.m-t-20 {
  margin-top: 20px!important;
}
</style>
@endsection

@section('content')
<div class="container">

    <div class="error">
    <div class="error-code m-b-10 m-t-20">Whoops <i class="fa fa-warning"></i></div>
        <h3 class="font-bold">Something went wrong...</h3>

        <div class="error-desc">
            Sorry, but something made our server angry. <br/>
            Try refreshing the page or click the button below to go back to the Homepage.
            <div>
                <a class=" login-detail-panel-button btn" href="/">
                    <i class="fa fa-arrow-left"></i>
                    Let's move!
                </a>
            </div>
        </div>
    </div>

</div>
@endsection

@push('footer_scripts')
{!! TidioChat::js() !!}
@endpush

resources/views/wizard.blade.php
@extends('layouts.bare')

@section('content')
<style>
	.caption {
		height: 80px;
		text-align: center;
		display: flex;
		justify-content: center;
		align-items: center;
	}
	.btn {
        -webkit-transition: 300ms;
        transition: 300ms;
	}
</style>
<div class="container">
    <div class="row">
        {!! Alert::info(trans('wizard.alert')) !!}
    </div>

    <div class="row">
        <div class="col-md-offset-2">
            <div class="col-md-5">
            {!! Panel::normal()->withHeader(trans('wizard.business.header'))->withBody(
                Thumbnail::image(asset('img/wizard/panel-business.png'))->caption(trans('wizard.business.caption')).
                Button::success(trans('wizard.business.btn'))->large()->block()->asLinkTo(route('wizard.pricing'))
                ) !!}
            </div>

            <div class="col-md-5">
            {!! Panel::normal()->withHeader(trans('wizard.user.header'))->withBody(
                Thumbnail::image(asset('img/wizard/panel-user.png'))->caption(trans('wizard.user.caption')).
                Button::primary(trans('wizard.user.btn'))->large()->block()->asLinkTo(route('user.directory.list'))
                ) !!}
            </div>
        </div>
    </div>
</div>
@endsection

@push('footer_scripts')
{!! TidioChat::js() !!}
@endpush