routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//////////////////
// ROOT CONTEXT //
//////////////////

Route::group(
    [
        'as'         => 'root.',
        'prefix'     => 'root',
        'namespace'  => 'Root',
        'middleware' => ['role:root'],
    ],
    function () {
        Route::get('dashboard', [
            'as'   => 'dashboard',
            'uses' => 'RootController@getIndex',
        ]);

        Route::get('sudo/{userId}', [
            'as'   => 'sudo',
            'uses' => 'RootController@getSudo',
        ])->where('userId', '\d*');
    }
);

//////////////////
// REGULAR AUTH //
//////////////////

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//////////
// AJAX //
//////////

Route::group(['namespace' => 'API'], function () {

    Route::post('booking', [
        'as'   => 'api.booking.action',
        'uses' => 'BookingController@postAction',
    ]);
});

///////////////////
// GUEST CONTEXT //
///////////////////

Route::group([], function () {

    ///////////////////////////
    // PRIVATE HOME / WIZARD //
    ///////////////////////////

    Route::get('home', ['as' => 'home', 'uses' => 'User\WizardController@getWizard'])->middleware('auth');

    ///////////////////////
    // LANGUAGE SWITCHER //
    ///////////////////////

    Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

    /////////////////
    // SOCIAL AUTH //
    /////////////////

    Route::get('social/login/redirect/{provider}', [
        'as'   => 'social.login',
        'uses' => 'Auth\OAuthController@redirectToProvider',
    ]);

    Route::get('social/login/{provider}', 'Auth\OAuthController@handleProviderCallback');

    /////////////////
    // PUBLIC HOME //
    /////////////////

    Route::get('/', 'WelcomeController@index');

    ///////////////////////////////////////
    // WHOOPS USER FRIENDLY ERROR SCREEN //
    ///////////////////////////////////////

    Route::get('whoops', [
        'as'   => 'whoops',
        'uses' => 'WhoopsController@display',
    ]);
});

//////////////////
// USER CONTEXT //
//////////////////

Route::group(['prefix' => 'user', 'middleware' => ['auth']], function () {

    // USER PREFERENCES
    Route::get('preferences', [
        'as'   => 'user.preferences',
        'uses' => 'User\UserPreferencesController@getPreferences',
        ]);
    Route::post('preferences', [
        'as'   => 'user.preferences',
        'uses' => 'User\UserPreferencesController@postPreferences',
        ]);

    Route::get('agenda', [
        'as'   => 'user.agenda',
        'uses' => 'User\AgendaController@getIndex',
    ]);
    Route::get('businesses/register/{plan?}', [
        'as'   => 'manager.business.register',
        'uses' => 'Manager\BusinessController@create',
    ]);
    Route::post('businesses/register', [
        'as'   => 'manager.business.store',
        'uses' => 'Manager\BusinessController@store',
    ]);
    Route::get('businesses', [
        'as'   => 'manager.business.index',
        'uses' => 'Manager\BusinessController@index',
    ]);
    Route::get('directory', [
        'as'   => 'user.directory.list',
        'uses' => 'User\BusinessController@getList',
    ]);
    Route::get('subscriptions', [
        'as'   => 'user.subscriptions',
        'uses' => 'User\BusinessController@getSubscriptions',
    ]);
    Route::get('dashboard', [
        'as'   => 'user.dashboard',
        'uses' => 'User\WizardController@getDashboard',
    ]);

    ////////////
    // WIZARD //
    ////////////
    Route::group(['as' => 'wizard.'], function () {
        Route::get('terms', [
            'as'   => 'terms',
            'uses' => 'User\WizardController@getTerms',
        ]);
        Route::get('wizard', [
            'as'   => 'welcome',
            'uses' => 'User\WizardController@getWelcome',
        ]);
        Route::get('pricing', [
            'as'   => 'pricing',
            'uses' => 'User\WizardController@getPricing',
        ]);
    });
});

////////////////////////////////////
// SELECTED BUSINESS SLUG CONTEXT //
////////////////////////////////////

Route::group(['prefix' => '{business}'], function ($business) {

    Route::get('ical/{token}', [
        'as'   => 'business.ical.download',
        'uses' => 'User\ICalController@download',
    ]);

    ///////////////////////////
    // BUSINESS USER CONTEXT //
    ///////////////////////////

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {

        // BOOKINGS
        Route::group(['prefix' => 'agenda', 'as' => 'booking.'], function () {
            Route::post('store', [
                'as'   => 'store',
                'uses' => 'AgendaController@postStore',
            ]);
            Route::get('book', [
                'as'   => 'book',
                'uses' => 'AgendaController@getAvailability',
            ]);
            Route::get('validate', [
                'as'   => 'validate',
                'uses' => 'AgendaController@getValidate',
            ]);
        });

        // BUSINESSES
        Route::group(['prefix' => 'businesses', 'as' => 'businesses.'], function () {
            Route::get('home', [
                'as'   => 'home',
                'uses' => 'BusinessController@getHome',
            ]);
        });
    });

    ////////////////////
    // USER RESOURCES //
    ////////////////////

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {

        Route::get('contact', [
            'as'   => 'business.contact.index',
            'uses' => 'ContactController@index',
        ]);
        Route::get('contact/create', [
            'as'   => 'business.contact.create',
            'uses' => 'ContactController@create',
        ]);
        Route::post('contact', [
            'as'   => 'business.contact.store',
            'uses' => 'ContactController@store',
        ]);
        Route::get('contact/{contact}', [
            'as'   => 'business.contact.show',
            'uses' => 'ContactController@show',
        ]);
        Route::get('contact/{contact}/edit', [
            'as'   => 'business.contact.edit',
            'uses' => 'ContactController@edit',
        ]);
        Route::put('contact/{contact}', [
            'as'   => 'business.contact.update',
            'uses' => 'ContactController@update',
        ]);
        Route::delete('contact/{contact}', [
            'as'   => 'business.contact.destroy',
            'uses' => 'ContactController@destroy',
        ]);
    });

    //////////////////////////////
    // BUSINESS MANAGER CONTEXT //
    //////////////////////////////

    Route::group(['prefix' => 'manage', 'namespace' => 'Manager'], function () {

        // BUSINESS PREFERENCES
        Route::get('preferences', [
            'as'   => 'manager.business.preferences',
            'uses' => 'BusinessPreferencesController@getPreferences',
            ]);
        Route::post('preferences', [
            'as'   => 'manager.business.preferences',
            'uses' => 'BusinessPreferencesController@postPreferences',
            ]);

        // AGENDA
        Route::get('agenda', [
            'as'   => 'manager.business.agenda.index',
            'uses' => 'BusinessAgendaController@getIndex',
        ]);
        Route::get('calendar', [
            'as'   => 'manager.business.agenda.calendar',
            'uses' => 'BusinessAgendaController@getCalendar',
        ]);

        // BUSINESS MANAGEMENT
        Route::get('dashboard', [
            'as'   => 'manager.business.show',
            'uses' => 'BusinessController@show',
        ]);
        Route::get('edit', [
            'as'   => 'manager.business.edit',
            'uses' => 'BusinessController@edit',
        ]);
        Route::put('', [
            'as'   => 'manager.business.update',
            'uses' => 'BusinessController@update',
        ]);
        Route::delete('', [
            'as'   => 'manager.business.destroy',
            'uses' => 'BusinessController@destroy',
        ]);

        // BUSINESS NOTIFICATIONS
        Route::get('notifications', [
            'as'   => 'manager.business.notifications.show',
            'uses' => 'BusinessNotificationsController@show',
            ]);

        // SEARCH
        Route::post('search', [
            'as'   => 'manager.search',
            'uses' => 'Search@postSearch',
        ]);

        // ADDRESSBOOK / CONTACT RESOURCE
        Route::group(['prefix' => 'contact'], function () {
            Route::get('', [
                'as'   => 'manager.addressbook.index',
                'uses' => 'AddressbookController@index',
            ]);
            Route::get('create', [
                'as'   => 'manager.addressbook.create',
                'uses' => 'AddressbookController@create',
            ]);
            Route::post('', [
                'as'   => 'manager.addressbook.store',
                'uses' => 'AddressbookController@store',
            ]);
            Route::get('{contact}', [
                'as'   => 'manager.addressbook.show',
                'uses' => 'AddressbookController@show',
            ]);
            Route::get('{contact}/edit', [
                'as'   => 'manager.addressbook.edit',
                'uses' => 'AddressbookController@edit',
            ]);
            Route::put('{contact}', [
                'as'   => 'manager.addressbook.update',
                'uses' => 'AddressbookController@update',
            ]);
            Route::delete('{contact}', [
                'as'   => 'manager.addressbook.destroy',

app/Http/Controllers/User/BusinessController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Fenos\Notifynder\Facades\Notifynder;
use Timegridio\Concierge\Concierge;
use Timegridio\Concierge\Models\Business;

class BusinessController extends Controller
{
    private $concierge;

    public function __construct(Concierge $concierge)
    {
        $this->concierge = $concierge;
    }

    /**
     * get Home.
     *
     * @param Business $business Business to display
     *
     * @return Response Rendered view for desired Business
     */
    public function getHome(Business $business)
    {
        logger()->info(__METHOD__);
        logger()->info(sprintf("businessId:%s businessSlug:'%s'", $business->id, $business->slug));

        $businessName = $business->name;
        Notifynder::category('user.visitedShowroom')
                   ->from('App\Models\User', auth()->id())
                   ->to('Timegridio\Concierge\Models\Business', $business->id)
                   ->url('http://localhost')
                   ->extra(compact('businessName'))
                   ->send();

        $available = $this->concierge->business($business)->isBookable('today', 30);

        $appointment = $business->bookings()->forContacts(auth()->user()->contacts)->active()->first();

        return view('user.businesses.show', compact('business', 'available', 'appointment'));
    }

    /**
     * get List.
     *
     * @return Response Rendered view of all existing Businesses
     */
    public function getList()
    {
        logger()->info(__METHOD__);

        $businesses = Business::where('listed', true)->get();

        return view('user.businesses.index', compact('businesses'));
    }

    ////////////////
    // FOR REVIEW //
    ////////////////

    /**
     * Gets the User profile Contacts that MAY BE subscribed to Businesses.
     *
     * @return Response Rendered view of the Contacts linked to the requesting User
     */
    public function getSubscriptions()
    {
        logger()->info(__METHOD__);

        $contacts = auth()->user()->contacts;

        return view('user.businesses.subscriptions', compact('contacts'));
    }
}

app/Http/Controllers/User/ICalController.php
<?php

namespace App\Http\Controllers\User;

use App\TG\Business\Token as BusinessToken;
use App\Http\Controllers\Controller;
use Eluceo\iCal\Component\Calendar;
use Eluceo\iCal\Component\Event;
use Timegridio\Concierge\Models\Business;
use Validator;

class ICalController extends Controller
{
    public function download(Business $business, $token)
    {
        logger()->info(__METHOD__);

        $validToken = with(new BusinessToken($business))->generate();

        $validator = Validator::make(compact('token'), [
            'token' => "bail|required|alpha_num|max:32|in:{$validToken}",
        ]);

        if ($validator->fails()) {
            abort(403);
        }

        // BEGIN
        $vCalendar = new Calendar($business->slug);

        $vCalendar->setPublishedTTL('PT1H');

        $events = $this->buildEvents($business);

        foreach ($events as $event) {
            $vCalendar->addComponent($event);
        }

        $type = 'text/calendar; charset=utf-8';
        $disposition = 'attachment; filename="calendar.ics"';

        $content = $vCalendar->render();

        return response($content)
                    ->header('Content-Type', $type)
                    ->header('Content-Disposition', $disposition);
    }

    protected function buildEvents(Business $business)
    {
        $businessAppointments = $business->bookings()->active()->get();

        $ownerAppointments = $business->owner()->appointments()->active()->get();

        $appointments = array_merge($businessAppointments->all(), $ownerAppointments->all());

        $events = [];

        foreach ($appointments as $appointment) {
            $vEvent = new Event();

            $startAt = new \DateTime($appointment->start_at->timezone($business->timezone)->toDateTimeString(), new \DateTimeZone($business->timezone));
            $endAt = new \DateTime($appointment->finish_at->timezone($business->timezone)->toDateTimeString(), new \DateTimeZone($business->timezone));

            $vEvent->setDtStart($startAt);
            $vEvent->setDtEnd($endAt);

            $vEvent->setStatus($this->mapStatus($appointment->status));

            $vEvent->setUniqueId($appointment->business->slug.':'.$appointment->code.'@timegrid.io');

            $summary = $appointment->contact->firstname.'/'.
                       $appointment->service->name.'@'.
                       $appointment->business->slug.
                       ' ['.$appointment->code.']';

            $vEvent->setSummary($summary);

            $vEvent->setDescription($appointment->comments);

            $vEvent->setUseTimezone(true);

            $events[] = $vEvent;
        }

        return $events;
    }

    /**
     * Map Timegridio\Concierge\Models\Appointment status into
     * Eluceo\iCal\Component\Event for ICal status compatibility
     */
    protected function mapStatus($status)
    {
        $mapping = [
            'R' => 'TENTATIVE',
            'C' => 'CONFIRMED',
            'A' => 'CANCELLED',
            'S' => 'CONFIRMED',
        ];

        return array_get($mapping, $status, 'TENTATIVE');
    }
}

app/Http/Controllers/User/UserPreferencesController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserPreferencesController extends Controller
{
    public function getPreferences()
    {
        logger()->info(__METHOD__);

        // BEGIN

        $parameters = config()->get('preferences.App\Models\User');
        $preferences = auth()->user()->preferences;

        return view('user.preferences.edit', compact('preferences', 'parameters'));
    }

    public function postPreferences(Request $request)
    {
        logger()->info(__METHOD__);

        // BEGIN

        $this->setUserPreferences($request->all());

        flash()->success(trans('user.msg.preferences.success'));

        return redirect()->back();
    }

    /////////////
    // HELPERS //
    /////////////

    protected function setUserPreferences($preferences)
    {
        // Get parameters from app configuration
        $parameters = config()->get('preferences.App\Models\User');

        // Get the keys of the parameters
        $parametersKeys = array_flip(array_keys($parameters));

        // Merge the user input with the parameter keys
        $mergedPreferences = array_intersect_key($preferences, $parametersKeys);

        foreach ($mergedPreferences as $key => $value) {
            logger()->info(sprintf(
                "set preference: UserId:%s key:%s='%s' type:%s",
                auth()->user()->id,
                $key,
                $value,
                $parameters[$key]['type']
            ));

            auth()->user()->pref($key, $value, $parameters[$key]['type']);
        }
    }
}

resources/views/user/_navmenu.blade.php
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ trans('app.nav.user.business.menu') }} <b class="caret"></b></a>
    <ul class="dropdown-menu">
    @if(isset($business))
        <li>
            <a href="{{ route('user.businesses.home', compact('business')) }}">{!! Icon::map_marker() !!}&nbsp;{{ $business->name }}</a>
        </li>
        <li class="nav-divider"></li>
    @endif
        <li>
            <a href="{{ route('user.directory.list') }}">{{ trans('app.nav.user.business.selector') }}</a>
        </li>
        <li>
            <a href="{{ route('user.subscriptions') }}">{{ trans('app.nav.user.business.my_subscriptions') }}</a>
        </li>
        <li class="nav-divider"></li>
        <li>
            <a href="{{ route('user.agenda') }}">{{ trans('app.nav.user.business.my_appointments') }}</a>
        </li>
        <li class="nav-divider"></li>
        <li>
            <a href="{{ route('wizard.welcome') }}">{{ trans('app.nav.wizard') }}</a>
        </li>
    </ul>
</li>

resources/views/user/_notifications-menu.blade.php
<!-- Notifications Menu -->
<li class="dropdown notifications-menu">
    <!-- Menu toggle button -->
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-calendar-check-o"></i>
        <span class="label {{ $appointments->count() > 0 ? 'label-warning' : 'label-default' }}">{{ $appointments->count() }}</span>
    </a>

    @foreach($appointments as $appointment)
    <ul class="dropdown-menu">
        <li>
            <!-- Inner Menu: contains the notifications -->
            <ul class="menu">
                <li><!-- start notification -->
                    <a href="{{ route('user.agenda') . '#' . $appointment->code() }}">
                        <i class="fa fa-calendar-check-o text-aqua"></i> {{ $appointment->service->name }} : {{ $appointment->business->name }}
                    </a>
                </li>
                <!-- end notification -->
            </ul>
        </li>
        <li class="footer"><a href="{{ route('user.agenda') }}">{{ trans('user.dashboard.card.agenda.button') }}</a></li>
    </ul>
    @endforeach
</li>

resources/views/user/dashboard.blade.php
@extends('layouts.user')

@section('content')
<div class="container-fluid">
    <div class="row">

    @if($appointmentsCount > 0)
        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail panel">
                <img src="{{asset('img/jumbo/do.png')}}" alt="">
                <div class="caption">
                    <h3>{{trans_choice('user.dashboard.card.agenda.title', $appointmentsCount)}}</h3>
                    <p>{{trans_choice('user.dashboard.card.agenda.description', $appointmentsCount)}}</p>
                    {!! Button::info(trans('user.dashboard.card.agenda.button'))
                        ->large()
                        ->block()
                        ->asLinkTo(route('user.agenda'))
                        !!}
                </div>
            </div>
        </div>
    @endif

    @if($subscriptionsCount > 0)
        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail panel">
                <img src="{{asset('img/jumbo/contact.png')}}" alt="">
                <div class="caption">
                    <h3>{{trans('user.dashboard.card.subscriptions.title', ['count' => $subscriptionsCount])}}</h3>
                    <p>{{trans('user.dashboard.card.subscriptions.description')}}</p>
                    {!! Button::info(trans('user.dashboard.card.subscriptions.button'))
                        ->large()
                        ->block()
                        ->asLinkTo(route('user.subscriptions'))
                        !!}
                </div>
            </div>
        </div>
    @endif

    @if($appointmentsCount + $subscriptionsCount == 0)
        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail panel">
                <img src="{{asset('img/jumbo/love.png')}}" alt="">
                <div class="caption">
                    <h3>{{trans('user.dashboard.card.directory.title')}}</h3>
                    <p>{{trans('user.dashboard.card.directory.description')}}</p>
                    {!! Button::info(trans('user.dashboard.card.directory.button'))
                        ->large()
                        ->block()
                        ->asLinkTo(route('user.directory.list'))
                        !!}
                </div>
            </div>
        </div>
    @endif

    </div>
</div>
@endsection

resources/views/user/notifications.blade.php
@extends('layouts.user')

@section('content')

    @foreach ($notifications as $notification)
        <div class="well">
            {{ $notification->from_id }} {{ $notification->text }}
        </div>
    @endforeach

@endsection