routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//////////////////
// ROOT CONTEXT //
//////////////////

Route::group(
    [
        'as'         => 'root.',
        'prefix'     => 'root',
        'namespace'  => 'Root',
        'middleware' => ['role:root'],
    ],
    function () {
        Route::get('dashboard', [
            'as'   => 'dashboard',
            'uses' => 'RootController@getIndex',
        ]);

        Route::get('sudo/{userId}', [
            'as'   => 'sudo',
            'uses' => 'RootController@getSudo',
        ])->where('userId', '\d*');
    }
);

//////////////////
// REGULAR AUTH //
//////////////////

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//////////
// AJAX //
//////////

Route::group(['namespace' => 'API'], function () {

    Route::post('booking', [
        'as'   => 'api.booking.action',
        'uses' => 'BookingController@postAction',
    ]);
});

///////////////////
// GUEST CONTEXT //
///////////////////

Route::group([], function () {

    ///////////////////////////
    // PRIVATE HOME / WIZARD //
    ///////////////////////////

    Route::get('home', ['as' => 'home', 'uses' => 'User\WizardController@getWizard'])->middleware('auth');

    ///////////////////////
    // LANGUAGE SWITCHER //
    ///////////////////////

    Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

    /////////////////
    // SOCIAL AUTH //
    /////////////////

    Route::get('social/login/redirect/{provider}', [
        'as'   => 'social.login',
        'uses' => 'Auth\OAuthController@redirectToProvider',
    ]);

    Route::get('social/login/{provider}', 'Auth\OAuthController@handleProviderCallback');

    /////////////////
    // PUBLIC HOME //
    /////////////////

    Route::get('/', 'WelcomeController@index');

    ///////////////////////////////////////
    // WHOOPS USER FRIENDLY ERROR SCREEN //
    ///////////////////////////////////////

    Route::get('whoops', [
        'as'   => 'whoops',
        'uses' => 'WhoopsController@display',
    ]);
});

//////////////////
// USER CONTEXT //
//////////////////

Route::group(['prefix' => 'user', 'middleware' => ['auth']], function () {

    // USER PREFERENCES
    Route::get('preferences', [
        'as'   => 'user.preferences',
        'uses' => 'User\UserPreferencesController@getPreferences',
        ]);
    Route::post('preferences', [
        'as'   => 'user.preferences',
        'uses' => 'User\UserPreferencesController@postPreferences',
        ]);

    Route::get('agenda', [
        'as'   => 'user.agenda',
        'uses' => 'User\AgendaController@getIndex',
    ]);
    Route::get('businesses/register/{plan?}', [
        'as'   => 'manager.business.register',
        'uses' => 'Manager\BusinessController@create',
    ]);
    Route::post('businesses/register', [
        'as'   => 'manager.business.store',
        'uses' => 'Manager\BusinessController@store',
    ]);
    Route::get('businesses', [
        'as'   => 'manager.business.index',
        'uses' => 'Manager\BusinessController@index',
    ]);
    Route::get('directory', [
        'as'   => 'user.directory.list',
        'uses' => 'User\BusinessController@getList',
    ]);
    Route::get('subscriptions', [
        'as'   => 'user.subscriptions',
        'uses' => 'User\BusinessController@getSubscriptions',
    ]);
    Route::get('dashboard', [
        'as'   => 'user.dashboard',
        'uses' => 'User\WizardController@getDashboard',
    ]);

    ////////////
    // WIZARD //
    ////////////
    Route::group(['as' => 'wizard.'], function () {
        Route::get('terms', [
            'as'   => 'terms',
            'uses' => 'User\WizardController@getTerms',
        ]);
        Route::get('wizard', [
            'as'   => 'welcome',
            'uses' => 'User\WizardController@getWelcome',
        ]);
        Route::get('pricing', [
            'as'   => 'pricing',
            'uses' => 'User\WizardController@getPricing',
        ]);
    });
});

////////////////////////////////////
// SELECTED BUSINESS SLUG CONTEXT //
////////////////////////////////////

Route::group(['prefix' => '{business}'], function ($business) {

    Route::get('ical/{token}', [
        'as'   => 'business.ical.download',
        'uses' => 'User\ICalController@download',
    ]);

    ///////////////////////////
    // BUSINESS USER CONTEXT //
    ///////////////////////////

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {

        // BOOKINGS
        Route::group(['prefix' => 'agenda', 'as' => 'booking.'], function () {
            Route::post('store', [
                'as'   => 'store',
                'uses' => 'AgendaController@postStore',
            ]);
            Route::get('book', [
                'as'   => 'book',
                'uses' => 'AgendaController@getAvailability',
            ]);
            Route::get('validate', [
                'as'   => 'validate',
                'uses' => 'AgendaController@getValidate',
            ]);
        });

        // BUSINESSES
        Route::group(['prefix' => 'businesses', 'as' => 'businesses.'], function () {
            Route::get('home', [
                'as'   => 'home',
                'uses' => 'BusinessController@getHome',
            ]);
        });
    });

    ////////////////////
    // USER RESOURCES //
    ////////////////////

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {

        Route::get('contact', [
            'as'   => 'business.contact.index',
            'uses' => 'ContactController@index',
        ]);
        Route::get('contact/create', [
            'as'   => 'business.contact.create',
            'uses' => 'ContactController@create',
        ]);
        Route::post('contact', [
            'as'   => 'business.contact.store',
            'uses' => 'ContactController@store',
        ]);
        Route::get('contact/{contact}', [
            'as'   => 'business.contact.show',
            'uses' => 'ContactController@show',
        ]);
        Route::get('contact/{contact}/edit', [
            'as'   => 'business.contact.edit',
            'uses' => 'ContactController@edit',
        ]);
        Route::put('contact/{contact}', [
            'as'   => 'business.contact.update',
            'uses' => 'ContactController@update',
        ]);
        Route::delete('contact/{contact}', [
            'as'   => 'business.contact.destroy',
            'uses' => 'ContactController@destroy',
        ]);
    });

    //////////////////////////////
    // BUSINESS MANAGER CONTEXT //
    //////////////////////////////

    Route::group(['prefix' => 'manage', 'namespace' => 'Manager'], function () {

        // BUSINESS PREFERENCES
        Route::get('preferences', [
            'as'   => 'manager.business.preferences',
            'uses' => 'BusinessPreferencesController@getPreferences',
            ]);
        Route::post('preferences', [
            'as'   => 'manager.business.preferences',
            'uses' => 'BusinessPreferencesController@postPreferences',
            ]);

        // AGENDA
        Route::get('agenda', [
            'as'   => 'manager.business.agenda.index',
            'uses' => 'BusinessAgendaController@getIndex',
        ]);
        Route::get('calendar', [
            'as'   => 'manager.business.agenda.calendar',
            'uses' => 'BusinessAgendaController@getCalendar',
        ]);

        // BUSINESS MANAGEMENT
        Route::get('dashboard', [
            'as'   => 'manager.business.show',
            'uses' => 'BusinessController@show',
        ]);
        Route::get('edit', [
            'as'   => 'manager.business.edit',
            'uses' => 'BusinessController@edit',
        ]);
        Route::put('', [
            'as'   => 'manager.business.update',
            'uses' => 'BusinessController@update',
        ]);
        Route::delete('', [
            'as'   => 'manager.business.destroy',
            'uses' => 'BusinessController@destroy',
        ]);

        // BUSINESS NOTIFICATIONS
        Route::get('notifications', [
            'as'   => 'manager.business.notifications.show',
            'uses' => 'BusinessNotificationsController@show',
            ]);

        // SEARCH
        Route::post('search', [
            'as'   => 'manager.search',
            'uses' => 'Search@postSearch',
        ]);

        // ADDRESSBOOK / CONTACT RESOURCE
        Route::group(['prefix' => 'contact'], function () {
            Route::get('', [
                'as'   => 'manager.addressbook.index',
                'uses' => 'AddressbookController@index',
            ]);
            Route::get('create', [
                'as'   => 'manager.addressbook.create',
                'uses' => 'AddressbookController@create',
            ]);
            Route::post('', [
                'as'   => 'manager.addressbook.store',
                'uses' => 'AddressbookController@store',
            ]);
            Route::get('{contact}', [
                'as'   => 'manager.addressbook.show',
                'uses' => 'AddressbookController@show',
            ]);
            Route::get('{contact}/edit', [
                'as'   => 'manager.addressbook.edit',
                'uses' => 'AddressbookController@edit',
            ]);
            Route::put('{contact}', [
                'as'   => 'manager.addressbook.update',
                'uses' => 'AddressbookController@update',
            ]);
            Route::delete('{contact}', [
                'as'   => 'manager.addressbook.destroy',

app/Http/Controllers/Guest/BusinessController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Http\Controllers\Controller;
use Timegridio\Concierge\Models\Business;
use Timegridio\Concierge\Models\Domain;

class BusinessController extends Controller
{
    /**
     * get Home.
     *
     * @param Business $business Business to display
     *
     * @return Response Rendered view for desired Business
     */
    public function getHome($slug)
    {
        logger()->info(__METHOD__);
        logger()->info(sprintf('slug:%s', $slug));

        if ($domain = Domain::where('slug', $slug)->first()) {
            return $this->getDomain($domain);
        }

        if ($business = Business::where('slug', $slug)->first()) {
            session()->set('guest.last-intended-business-home', $slug);

            return view('guest.businesses.show', compact('business'));
        }

        session()->forget('guest.last-intended-business-home');

        $baseurl = url()->to('/'.$slug);

        flash()->success(trans('app.msg.slug_is_available', compact('baseurl')));

        return redirect()->to('/login');
    }

    /**
     * get Domain.
     *
     * @return Response Rendered view of all existing Businesses belonging to Domain
     */
    public function getDomain(Domain $domain)
    {
        logger()->info(__METHOD__);

        $businesses = $domain->businesses;

        if (1 == $businesses->count()) {
            return redirect(route('guest.business.home', $businesses->first()));
        }

        return view('guest.businesses.index', compact('businesses'));
    }
}

app/Http/Controllers/User/BusinessController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Fenos\Notifynder\Facades\Notifynder;
use Timegridio\Concierge\Concierge;
use Timegridio\Concierge\Models\Business;

class BusinessController extends Controller
{
    private $concierge;

    public function __construct(Concierge $concierge)
    {
        $this->concierge = $concierge;
    }

    /**
     * get Home.
     *
     * @param Business $business Business to display
     *
     * @return Response Rendered view for desired Business
     */
    public function getHome(Business $business)
    {
        logger()->info(__METHOD__);
        logger()->info(sprintf("businessId:%s businessSlug:'%s'", $business->id, $business->slug));

        $businessName = $business->name;
        Notifynder::category('user.visitedShowroom')
                   ->from('App\Models\User', auth()->id())
                   ->to('Timegridio\Concierge\Models\Business', $business->id)
                   ->url('http://localhost')
                   ->extra(compact('businessName'))
                   ->send();

        $available = $this->concierge->business($business)->isBookable('today', 30);

        $appointment = $business->bookings()->forContacts(auth()->user()->contacts)->active()->first();

        return view('user.businesses.show', compact('business', 'available', 'appointment'));
    }

    /**
     * get List.
     *
     * @return Response Rendered view of all existing Businesses
     */
    public function getList()
    {
        logger()->info(__METHOD__);

        $businesses = Business::where('listed', true)->get();

        return view('user.businesses.index', compact('businesses'));
    }

    ////////////////
    // FOR REVIEW //
    ////////////////

    /**
     * Gets the User profile Contacts that MAY BE subscribed to Businesses.
     *
     * @return Response Rendered view of the Contacts linked to the requesting User
     */
    public function getSubscriptions()
    {
        logger()->info(__METHOD__);

        $contacts = auth()->user()->contacts;

        return view('user.businesses.subscriptions', compact('contacts'));
    }
}

app/Http/Controllers/User/ICalController.php
<?php

namespace App\Http\Controllers\User;

use App\TG\Business\Token as BusinessToken;
use App\Http\Controllers\Controller;
use Eluceo\iCal\Component\Calendar;
use Eluceo\iCal\Component\Event;
use Timegridio\Concierge\Models\Business;
use Validator;

class ICalController extends Controller
{
    public function download(Business $business, $token)
    {
        logger()->info(__METHOD__);

        $validToken = with(new BusinessToken($business))->generate();

        $validator = Validator::make(compact('token'), [
            'token' => "bail|required|alpha_num|max:32|in:{$validToken}",
        ]);

        if ($validator->fails()) {
            abort(403);
        }

        // BEGIN
        $vCalendar = new Calendar($business->slug);

        $vCalendar->setPublishedTTL('PT1H');

        $events = $this->buildEvents($business);

        foreach ($events as $event) {
            $vCalendar->addComponent($event);
        }

        $type = 'text/calendar; charset=utf-8';
        $disposition = 'attachment; filename="calendar.ics"';

        $content = $vCalendar->render();

        return response($content)
                    ->header('Content-Type', $type)
                    ->header('Content-Disposition', $disposition);
    }

    protected function buildEvents(Business $business)
    {
        $businessAppointments = $business->bookings()->active()->get();

        $ownerAppointments = $business->owner()->appointments()->active()->get();

        $appointments = array_merge($businessAppointments->all(), $ownerAppointments->all());

        $events = [];

        foreach ($appointments as $appointment) {
            $vEvent = new Event();

            $startAt = new \DateTime($appointment->start_at->timezone($business->timezone)->toDateTimeString(), new \DateTimeZone($business->timezone));
            $endAt = new \DateTime($appointment->finish_at->timezone($business->timezone)->toDateTimeString(), new \DateTimeZone($business->timezone));

            $vEvent->setDtStart($startAt);
            $vEvent->setDtEnd($endAt);

            $vEvent->setStatus($this->mapStatus($appointment->status));

            $vEvent->setUniqueId($appointment->business->slug.':'.$appointment->code.'@timegrid.io');

            $summary = $appointment->contact->firstname.'/'.
                       $appointment->service->name.'@'.
                       $appointment->business->slug.
                       ' ['.$appointment->code.']';

            $vEvent->setSummary($summary);

            $vEvent->setDescription($appointment->comments);

            $vEvent->setUseTimezone(true);

            $events[] = $vEvent;
        }

        return $events;
    }

    /**
     * Map Timegridio\Concierge\Models\Appointment status into
     * Eluceo\iCal\Component\Event for ICal status compatibility
     */
    protected function mapStatus($status)
    {
        $mapping = [
            'R' => 'TENTATIVE',
            'C' => 'CONFIRMED',
            'A' => 'CANCELLED',
            'S' => 'CONFIRMED',
        ];

        return array_get($mapping, $status, 'TENTATIVE');
    }
}

resources/views/user/businesses/_row.blade.php
<a href="{{ route('user.businesses.home', compact('business')) }}" class="list-group-item">
    <div class="media col-md-3">
        <figure class="pull-left">
            {!! $business->facebookImg('normal') !!}
        </figure>
    </div>
    <div class="col-md-6">
        <h4 class="list-group-item-heading"> {{ str_limit($business->name, 50) }} </h4>
        <p class="list-group-item-text">
            <p>
                <i class="glyphicon glyphicon-home"></i>&nbsp;
                {!! trans('app.business.category.'.strtolower($business->category->slug)) !!}
            </p>
        </p>
        <p class="list-group-item-text multiline-list-item">
            {{ str_limit(strip_tags(Markdown::convertToHtml(strip_tags($business->description))), 400) }}
        </p>
    </div>
    <div class="col-md-3 text-center">
        <h2> {{ $business->subscriptionsCount }} <small> {{ trans('user.businesses.subscriptions.title') }} </small></h2>
        <button type="button" class="btn btn-default btn-lg btn-block"> {{ trans('user.appointments.btn.book') }} </button>
    </div>
</a>

resources/views/user/businesses/index.blade.php
@extends('layouts.user')

@section('css')
@parent
<style>
.glyphicon {
    margin-bottom: 4px;
    margin-right: 10px;
    color: #999;
}
a.list-group-item {
    height:auto;
    min-height:220px;
}
a.list-group-item.active small {
    color:#fff;
}
.list-group-item-heading {
    margin-top: 16px;
}

.multiline-list-item {
    word-wrap: break-word;
}
</style>
@endsection

@section('title', trans('user.businesses.index.title'))

@section('content')
<div class="container-fluid">
    <div class="row">
        
        <div class="list-group">
            @if ($businesses->isEmpty())
                {{ trans('user.businesses.list.no_businesses') }}
            @else
                @foreach ($businesses as $business)
                    @include('user.businesses._row', compact('business'))
                @endforeach
            @endif
        </div>

        @if($user->hasBusiness())
            {!! Button::normal(trans('user.businesses.index.btn.manage'))->asLinkTo( route('manager.business.index') )->block() !!}
        @else
            {!! Button::primary(trans('user.businesses.index.btn.create'))->asLinkTo( route('manager.business.register') )->block() !!}
        @endif

    </div>
</div>
@endsection

resources/views/user/businesses/show.blade.php
@extends('layouts.user')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">

                <div class="panel-heading">
                    {!! Icon::star() !!}&nbsp;{{ $business->subscriptionsCount }}
                </div>

                    <ul class="list-group">

                        <li class="list-group-item text-center">
                            <h1>{!! $business->name !!}</h1>
                        </li>

                        <li class="list-group-item">
                            {!! $business->industryIcon !!}
                        </li>

                        <li class="list-group-item">
                            <div class="row">
                            <div class="col-md-12">
                                <div class="media">
                                  <div class="media-left media-top hidden-xs hidden-sm">
                                    <a href="#">{!! $business->facebookImg('normal') !!}</a>
                                  </div>
                                  <div class="media-body">
                                    <div class="{{ $business->pref('description_div_class') }}">
                                        <h5>{!! Markdown::convertToHtml(strip_tags($business->description)) !!}</h5>
                                    </div>
                                  </div>
                                </div>
                            </div>
                            </div>
                        </li>

                        @if ($business->phone || $business->postal_address)
                        <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-4">
                                    @if ($business->pref('show_phone') && $business->phone)
                                        {!! Icon::phone() !!}&nbsp;{{ $business->phone }}
                                    @endif
                                    </div>
                                    <div class="col-md-8">
                                    @if ($business->pref('show_postal_address') && $business->postal_address)
                                        {!! Icon::home() !!}&nbsp;{{ $business->postal_address }}
                                    @endif
                                    </div>
                                </div>
                        </li>
                        @endif

                        @if ($business->pref('show_map') && $business->postal_address)
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    {!! $business->staticMap(11) !!}
                                </div>
                            </div>
                        </li>
                        @endif

                        @if (!($appointment and $appointment->isActive()))
                        <li class="list-group-item">
                            @if ($user->getContactSubscribedTo($business->id) === null)
                                {!! Button::large()->primary(trans('user.business.btn.subscribe_to', ['business' => $business->name]))
                                                   ->asLinkTo(route('user.business.contact.create', $business))
                                                   ->withIcon(Icon::star())->block() !!}
                            @else
                                @if($available)
                                    {!! Button::large()->success(trans('user.appointments.btn.book'))
                                                       ->asLinkTo(route('user.booking.book', $business))
                                                       ->withIcon(Icon::calendar())->block() !!}
                                @else
                                    <div class="alert alert-warning">{{ trans('user.appointments.alert.no_vacancies') }}</div>
                                @endif
                            @endif
                        </li>
                        @endif

                        @if($user->isOwnerOf($business->id))
                        <li class="list-group-item">
                            {!! Button::primary(trans('user.go_to_business_dashboard', ['business' => $business->name]))->withIcon(Icon::dashboard())->block()->large()->asLinkTo(route('manager.business.show', $business), $business->name) !!}
                        </li>
                        @endif

                    </ul>
                
            </div>

            @if ($appointment)
            {!! Form::open(['id' => 'postAppointmentStatus', 'method' => 'post', 'route' => ['api.booking.action']]) !!}
                {!! $appointment->panel !!}
            {!! Form::close() !!}
            @endif

        </div>
    </div>
</div>
@endsection

@push('footer_scripts')
<script>
$(document).ready(function(){

function prepareEvents(){

        console.log('prepareEvents()');

        var form = $('#postAppointmentStatus');
        var button = $('.action');
        var buttons = $('.actiongroup');
        var token = $('input[name=_token]');

        button.click(function (event){

        event.preventDefault();

        var business = $(this).data('business');
        var appointment = $(this).data('appointment');
        var action = $(this).data('action');
        var code = $(this).data('code');
        var panel = $('#'+code);

        $(this).parent().hide();

            $.ajax({
                url: form.attr('action'),
                method: 'post',
                dataType: 'json',
                headers: {
                    'X-CSRF-TOKEN': token.val()
                },
                data: { business: business, appointment: appointment, action: action, widget: 'panel' }
            }).done(function (data) {
                    console.log('AJAX Done');
                    $('#'+code).replaceWith(data.html);
            }).fail(function (data) {
                    console.log('AJAX Fail');
            }).always(function (data) {
                    $(this).parent().show();
                    // prepareEvents();
                    console.log('AJAX Finish');
                    console.log(data);
            });
        });
    }

prepareEvents();

});
</script>
@endpush

resources/views/user/businesses/subscriptions.blade.php
@extends('layouts.user')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">{{ trans('user.businesses.subscriptions.title') }}</div>

                <div class="panel-body">
                    @if (!$contacts->isEmpty())
                    <table class="table table-condensed">
	                    @foreach ($contacts as $contact)
	                        <tr>
	                            <td>{{ $contact->nin }}</td>
	                            <td>{{ $contact->firstname }}</td>
	                            <td>{{ $contact->lastname }}</td>
	                            <td>{{ $contact->email }}</td>
	                            <td>
	                            @if($contact->businesses()->count())
	                                @foreach ($contact->businesses as $business)
	                                    {!! Button::normal($business->slug)->asLinkTo(route('user.business.contact.show', [$business, $contact])) !!}
	                                @endforeach
	                            @endif
	                            </td>
	                        </tr>
	                    @endforeach
	                    </table>
                    @else
                    	{{ trans('user.businesses.subscriptions.none_found') }}
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection